### ISSUE TITLE
Possible inconsistencies with the numbers reported in the paper?

### ISSUE THREAD

**Issue by swarnaHub** [gabrielStanovsky/oie-benchmark#7]
Hi Gabriel,

I have a couple of doubts. Please let me know if I am going wrong somewhere.

1. Since I could not find CoNLL 2009 English corpus anywhere, I was working with the oie_corpus snapshot you had shared. If I am not wrong, each line in 'all.oie' file is supposed to count as one extraction and that makes it a total of 8481 extractions, while in the paper in Table 2 you have mentioned the total number of extractions to be 10,359. Please let me know if I am missing something here.

2. I am also unable to reproduce the PR curve that you have given in the paper. I was however able to regenerate the curve given in 'eval/eval.png' but that doesn't seem to match with what you have in the paper.

**Comment by gabrielStanovsky** [comment]
Hi @swarnaHub, you're correct on both points.
They both stem from some changes I made after publishing the paper.  
See details below, including how to obtain the original corpus. I'll add these points to the documentation.
Please let me know what you think.

Thanks!

1. In a follow-up work, I removed extractions that had only pronouns as one of the arguments, and that the same extraction appeared using the entity the pronoun was referring to. 
For example:
```John went home, he was hungry```
The original corpus would have had both extractions:
   1. ("John", "was", "hungry")
   2. ("he", "was", "hungry")

While in this version of the corpus I remove extraction (2), following the observation that I penalize some systems for not extracting it, where they may be doing that on purpose.
Evaluating OIE, as with other semantic tasks (translation, etc.), has some subtleties, but we thought that since the systems ordering didn't change so much, this one's pretty minor.
I uploaded the original corpus to the repo, If your'e interested (with 10359 extractions, as reported in the paper). You can find it [here](https://github.com/gabrielStanovsky/oie-benchmark/blob/master/snapshot_oie_corpus_with_pronouns.tar.gz).

2. Somewhat similar to the first point, we changed the evaluation scripts slightly to be more lenient. I don't think that this changes the ordering of the systems, and as I mention before, I don't think that the absolute numbers themselves are that meaningful, rather the relative performance of the different systems.

**Comment by gabrielStanovsky** [comment]
Sorry, I had the wrong link in my comment above, fixed that now.

**Comment by swarnaHub** [comment]
Thanks a lot Gabriel! I along with Dr. Mausam have recently released Open IE 5.0, where we have handled numerical and conjunctive sentences better. We wanted to test Open IE 5.0 on your benchmark dataset and see how much better we are able to do wrt Open IE 4 and the other systems. I'll probably go with the corpus you had mentioned in the paper. Thanks for sharing it. :)

**Comment by gabrielStanovsky** [comment]
Sounds great! I'd be happy to hear how it goes! 
Let me know if there's anything I can do to help.

I guess I can close this issue for now?

**Comment by swarnaHub** [comment]
Sure. I'll let you know in case I need something.
